### ISSUE TITLE
I would like to integrate PushEx with an existing Phoenix application

### ISSUE THREAD

**Issue by mauricionr** [pushex-project/pushex#36]
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sb8244** [comment]
Hey, sorry for dropping off here. I'm going to look into how to go about doing this over the next week.

**Comment by sb8244** [comment]
Hey @mauricionr 

Can you give me your thoughts on how an app like this should be deployed alongside an existing phoenix app? One of the things I've been waffling on is that I don't believe an app like this should be deployed frequently (because gaps in connectivity are inevitable). However, I believe a core app will be deployed to frequently.

I'm a bit nervous to support integration into an existing app because of this.

-Steve

**Comment by mauricionr** [comment]
> Hey @mauricionr
> 
> Can you give me your thoughts on how an app like this should be deployed alongside an existing phoenix app? One of the things I've been waffling on is that I don't believe an app like this should be deployed frequently (because gaps in connectivity are inevitable). However, I believe a core app will be deployed to frequently.
> 
> I'm a bit nervous to support integration into an existing app because of this. I don't want to prescribe to you what you can / can't do, but I don't want to actively support something that will put you in a bad situation. I have not decided this yet, I'm still waffling on it which is why it has taken so long (and I'm writing a book which has taken a lot of time).
> 
> -Steve

I think that if the pushex was added to an existing project, the people who added it should know that it's not good deploy frequently and know the problems about deploying frequently(warn in the docs).

and the best practice is to create an isolated project to not deploy frequently, should be added as best practice in docs

what do you think?

-Mauricio

**Comment by ivanovv** [comment]
To add to what @mauricionr has already stated – sometimes the phoenix app is not the main app (I guess rails + phoenix couple is rather frequent out there). And because the phoenix usually handles websockets then adding another solution along side phoenix will double the number of sockets needed. For _many_ apps out there the difference between 50K-60K connections and 100K-120K will be a big thing.

Though I have to admit, with pushex being completely independent, it is possible to move it to a separate host with a different DNS name and put a separate load balancer in front of it (if needed). That will allow to mitigate 2x connections issue, at the expense of adding complexity to the project infrastructure

**Comment by sb8244** [comment]
First, I want to apologize for dropping off on this issue. I meant to respond and archived the email. That's my bad.

I was pretty opposed to this over time, and was going to indicate as such previously. However, I'm more open to it now and am willing to explore how to integrate with an existing app.

One thing that I don't think will change (at least not without a very major change to Pushex) is that Pushex.Socket will remain the Phoenix.Socket implementation used. So, it would still be 2x the connections if you want to use Pushex alongside an existing app that already has 1 socket per user.

I have done a few things with embedding Phoenix apps inside of another app, but it's honestly a bit dicey still. Are there any best practices that you're aware of for how to integrate 2 Phoenix.Endpoints together without requiring several touchpoints added to the existing app?

For example, it would be easy to add some macros that can be added to an existing Endpoint / Router. These macros could setup what's needed for Pushex, but it's pretty heavy. Ideally, Pushex would be completely isolated from your app (separate Endpoint, Router, PubSub), but you could call `Pushex.broadcast` in Elixir and it would work properly.

**Comment by sb8244** [comment]
I'm about 5 years too late here.

I'm using PushEx in a new project and will be doing this work. I have a proof-of-concept working right now with fairly minimal changes / overhead required.

I will re-open this and mark it closed once done.

**Comment by sb8244** [comment]
Here are the steps I took to get PushEx running in standalone mode: https://github.com/pushex-project/pushex/pull/46#issue-2764649519

I will say that it's still significantly easier to add application push support using this vs doing it manually. I had everything up and running pretty quickly with this, although required some library changes (2.2.0) to support it.
